version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports: ['9000:9000']
    container_name: symfony5_microkernel
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/symfony5_microkernel
  mysql:
    image: mysql:8.0.22
    container_name: symfony5_microkernel_mysql
    ports: [ '3306:3306' ]
    restart: on-failure
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
volumes:
  mysql_volume:
    name: mysql_volume
    driver: local


